# Generated by Django 3.0.4 on 2020-03-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('tipo', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=5)),
                ('simbolo', models.CharField(max_length=3)),
                ('compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('venda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.Moeda')),
            ],
        ),
    ]
